### ISSUE TITLE
So

### ISSUE THREAD

**Issue by Ironholds** [bearloga/greenr#1]
Is this the "you draft in R, I implement in C++" dealie?

**Comment by Ironholds** [comment]
(and if so, can we pick a more transparent name? fastml or something ;p)

**Comment by Ironholds** [comment]
Assuming this is indeed a "you draft in R, I imlement in C++". Reimplementing in C++, all subtle-like ;).

**Comment by bearloga** [comment]
Sorry I didn't reply earlier. I'm still not used to checking GitHub for comments and messages and whatnot. Feel like *fastml* implies more than what I'm capable of. Like, I'm implementing decision trees and random forests right now in R, and that's really the most I want to and can do with this package. But implementing stuff like SVN and neural nets and other ML methods/algorithms from scratch is so outside my skill set.

I'm OK with renaming the package if you think of a better tree/forest-related name :D (even if I am quite fond of *greenr*)

**Comment by Ironholds** [comment]
I like greenr! I didn't get the forest/tree theme. Let's do it :dancers:
